import * as fs from 'fs'
import * as path from 'path'

const resolve = path.resolve

describe('viewer UI shell', () => {
  it('shows a PST list and no upload controls', () => {
    const html = fs.readFileSync(resolve('./example/public/index.html'), 'utf8')
    const script = fs.readFileSync(resolve('./example/public/app.js'), 'utf8')
    const styles = fs.readFileSync(resolve('./example/public/styles.css'), 'utf8')

    expect(html).toContain('content="light dark"')
    expect(html).toContain('id="auth-screen"')
    expect(html).toContain('class="auth-screen"')
    expect(html).toContain('id="auth-title"')
    expect(html).toContain('id="auth-section-title"')
    expect(html).toContain('id="auth-form"')
    expect(html).toContain('id="auth-username"')
    expect(html).toContain('id="auth-password"')
    expect(html).toContain('id="auth-submit"')
    expect(html).toContain('class="auth-card-top"')
    expect(html).toContain('class="auth-brand"')
    expect(html).toContain('class="auth-mark"')
    expect(html).toContain('class="auth-divider"')
    expect(html).toContain('class="auth-section"')
    expect(html).toContain('class="auth-footer"')
    expect(html).toContain('id="app-shell"')
    expect(html).toContain('id="auth-user"')
    expect(html).toContain('id="settings-button"')
    expect(html).toContain('id="settings-menu"')
    expect(html).toContain('id="manage-users-button"')
    expect(html).toContain('id="activity-log-button"')
    expect(html).toContain('id="auth-logout"')
    expect(html).toContain('id="shell-theme-toggle"')
    expect(html).toContain('data-theme-toggle')
    expect(html).toContain("document.documentElement.dataset.theme = 'dark'")
    expect(html).toContain('PST Mail Explorer')
    expect(html).toContain('Sign in to continue')
    expect(html).toContain('Use your local username and password to unlock the platform.')
    expect(html).toContain('Developed by DigiVectra DevOps')
    expect(html).toContain('For access or investigation support, contact the Compliance Engineering team.')
    expect(html).toContain('id="user-management-modal"')
    expect(html).toContain('id="user-management-close"')
    expect(html).toContain('id="user-management-form"')
    expect(html).toContain('id="user-management-username"')
    expect(html).toContain('id="user-management-password"')
    expect(html).toContain('id="user-management-submit"')
    expect(html).toContain('id="user-management-message"')
    expect(html).toContain('id="user-list"')
    expect(html).toContain('id="user-count-badge"')
    expect(html).toContain('id="user-activity-title"')
    expect(html).toContain('id="user-activity-selected"')
    expect(html).toContain('id="user-activity-message"')
    expect(html).toContain('id="user-activity-list"')
    expect(html).toContain('id="user-activity-count-badge"')
    expect(html).toContain('id="user-activity-export"')
    expect(html).toContain('id="user-activity-refresh"')
    expect(html).toContain('id="activity-log-modal"')
    expect(html).toContain('id="activity-log-export"')
    expect(html).toContain('id="activity-log-close"')
    expect(html).toContain('id="activity-log-refresh"')
    expect(html).toContain('id="activity-log-message"')
    expect(html).toContain('id="activity-log-list"')
    expect(html).toContain('id="activity-log-count-badge"')
    expect(html).toContain('id="pst-count-badge"')
    expect(html).toContain('id="case-select"')
    expect(html).toContain('id="scope-select"')
    expect(html).toContain('id="pst-filter"')
    expect(html).toContain('id="search-button"')
    expect(html).toContain('id="search-scope-select"')
    expect(html).toContain('id="flagged-bundle-scope-select"')
    expect(html).toContain('id="flagged-bundle-button"')
    expect(html).toContain('bundle-toolbar')
    expect(html).toContain('id="hidden-filters-dropdown"')
    expect(html).toContain('id="hidden-filters-toggle"')
    expect(html).toContain('id="hidden-filters-count"')
    expect(html).toContain('id="scope-count-badge"')
    expect(html).toContain('id="pst-list"')
    expect(html).toContain('id="catalog-mode-toggle"')
    expect(html).toContain('id="mailboxes-section-title"')
    expect(html).toContain('data-action="close-user-management"')
    expect(html).toContain('data-action="close-activity-log"')
    expect(html).toContain('class="button-icon"')
    expect(html).toContain('ghost-button small icon-button')
    expect(html).toContain('aria-label="Export user activity as CSV"')
    expect(html).toContain('aria-label="Export activity log as CSV"')
    expect(html).toContain('search-utils.js')
    expect(html).toContain('id="review-flagged-toggle"')
    expect(html).toContain('id="review-tagged-toggle"')
    expect(html).toContain('placeholder="Keywords, &quot;phrases&quot;, + AND, | OR"')
    expect(html).toContain('Select a mailbox to load folders with content.')
    expect(html).not.toContain('navigator-header')
    expect(html).not.toContain('PST Browser')
    expect(script).toContain('scopeSelect')
    expect(script).toContain('caseSelect')
    expect(script).toContain('pstFilter')
    expect(script).toContain('searchButton')
    expect(script).toContain('scopePath')
    expect(script).toContain('searchScope')
    expect(script).toContain('flaggedBundleScopeSelect')
    expect(script).toContain('flaggedBundleButton')
    expect(script).toContain('mailboxScopeView')
    expect(script).not.toContain('searchModeSelect')
    expect(script).toContain('deriveSearchMode')
    expect(script).toContain('showAuthScreen')
    expect(script).toContain('showViewerShell')
    expect(script).toContain('loadAuthState')
    expect(script).toContain('loadAuthUsers')
    expect(script).toContain('wireAuthEvents')
    expect(script).toContain('wireUserManagementEvents')
    expect(script).toContain('toggleSettingsMenu')
    expect(script).toContain('openUserManagementModal')
    expect(script).toContain('closeUserManagementModal')
    expect(script).toContain('openActivityLogModal')
    expect(script).toContain('closeActivityLogModal')
    expect(script).toContain('loadActivityLog')
    expect(script).toContain('buildActivityLogCsvUrl')
    expect(script).toContain('downloadActivityLogCsv')
    expect(script).toContain('wireThemeEvents')
    expect(script).toContain('readThemePreference')
    expect(script).toContain('persistThemePreference')
    expect(script).toContain('applyTheme')
    expect(script).toContain('toggleTheme')
    expect(script).toContain('/api/auth/me')
    expect(script).toContain('/api/auth/login')
    expect(script).toContain('/api/auth/logout')
    expect(script).toContain('/api/auth/users')
    expect(script).toContain("credentials: 'include'")
    expect(script).toContain('pst-mail-explorer.theme')
    expect(script).toContain('themeToggleButtons')
    expect(script).toContain('authCanManageUsers')
    expect(script).toContain('selectedUserActivityUsername')
    expect(script).toContain('userActivityLoading')
    expect(script).toContain('userActivityLoaded')
    expect(script).toContain('userActivityEntries')
    expect(script).toContain('activityLogOpen')
    expect(script).toContain('activityLogLoading')
    expect(script).toContain('activityLogLoaded')
    expect(script).toContain('settingsMenu')
    expect(script).toContain('settingsButton')
    expect(script).toContain('manageUsersButton')
    expect(script).toContain('activityLogButton')
    expect(script).toContain('userManagementModal')
    expect(script).toContain('userManagementClose')
    expect(script).toContain('userActivitySelected')
    expect(script).toContain('userActivityMessage')
    expect(script).toContain('userActivityList')
    expect(script).toContain('userActivityCountBadge')
    expect(script).toContain('userActivityExport')
    expect(script).toContain('userActivityRefresh')
    expect(script).toContain('loadUserActivityLog')
    expect(script).toContain('selectUserActivity')
    expect(script).toContain('deleteUser')
    expect(script).toContain('renderTrashIcon')
    expect(script).toContain('renderDownloadIcon')
    expect(script).toContain('attachment-unavailable')
    expect(script).toContain('Attachment bytes are not stored in this PST.')
    expect(script).toContain('data-action="select-user-activity"')
    expect(script).toContain('data-action="delete-user"')
    expect(script).toContain('activityLogModal')
    expect(script).toContain('activityLogClose')
    expect(script).toContain('activityLogExport')
    expect(script).toContain('/api/activity-log.csv')
    expect(script).toContain("color-scheme: ${isDark ? 'dark' : 'light'}")
    expect(script).toContain('const label = `${getSearchLabel(entry.scopePath)} (${entry.fileCount})`')
    expect(script).toContain("return parts[parts.length - 1] || 'PST root'")
    expect(script).toContain('All PSTs')
    expect(script).toContain('ALL_PSTS_SCOPE_VALUE')
    expect(script).toContain('catalogMode')
    expect(script).toContain('getCatalogModeLabel')
    expect(script).toContain('getCatalogEndpoint')
    expect(script).toContain('renderPstRow')
    expect(script).toContain('remove-pst')
    expect(script).toContain('restore-pst')
    expect(script).toContain('getMailboxEntriesForDisplay')
    expect(script).toContain('normalizeSearchResultsPage')
    expect(script).toContain('resolveMessageId')
    expect(script).toContain('hiddenFiltersDropdown')
    expect(script).toContain('hiddenFiltersToggle')
    expect(script).toContain('hiddenFiltersCount')
    expect(script).toContain('hiddenFiltersPanel')
    expect(script).toContain('hiddenFiltersOpen')
    expect(script).toContain('data-action="close-hidden-filters"')
    expect(script).toContain('refreshActiveVisibleMessages')
    expect(script).toContain('bundleScope')
    expect(script).toContain('downloadFlaggedBundle')
    expect(script).toContain('buildFlaggedBundleDownloadUrl')
    expect(script).toContain('inline-filter-button')
    expect(script).toContain('catalogModeToggle')
    expect(script).toContain('canReviewMessage')
    expect(script).toContain("detail.kind === 'appointment'")
    expect(script).toContain('mail and appointment items only')
    expect(script).toContain('collectFoldersWithContent')
    expect(script).toContain('flat-folder-list')
    expect(script).toContain('/api/psts')
    expect(script).toContain('/api/psts/removed')
    expect(script).toContain('/api/psts/remove')
    expect(script).toContain('/api/psts/restore')
    expect(script).toContain('/api/psts/open')
    expect(script).toContain('/api/search')
    expect(script).toContain('/api/search/filters')
    expect(script).toContain('/api/exports/flagged.zip')
    expect(script).toContain('/review')
    expect(script).toContain('toggle-review-flag')
    expect(script).toContain('indexedMessageCount')
    expect(script).toContain('authEnabled')
    expect(script).toContain('authUser')
    expect(script).toContain('authUsers')
    expect(script).toContain('canManageUsers')
    expect(script).not.toContain('userManagementSection')
    expect(styles).toContain('[hidden] {')
    expect(styles).toContain('#app-shell[hidden]')
    expect(styles).toContain('.auth-screen')
    expect(styles).toContain('.auth-shell')
    expect(styles).toContain('.auth-card')
    expect(styles).toContain('.auth-card-top')
    expect(styles).toContain('.auth-brand')
    expect(styles).toContain('.auth-mark')
    expect(styles).toContain('.auth-mark-icon')
    expect(styles).toContain('.auth-divider')
    expect(styles).toContain('.auth-section')
    expect(styles).toContain('.auth-footer')
    expect(styles).toContain('.settings-menu-shell')
    expect(styles).toContain('.modal-overlay')
    expect(styles).toContain('.modal-header-actions')
    expect(styles).toContain('.user-management-body')
    expect(styles).toContain('.user-management-sidebar')
    expect(styles).toContain('.user-management-summary')
    expect(styles).toContain('.user-list')
    expect(styles).toContain('.user-item-row')
    expect(styles).toContain('.user-item-select')
    expect(styles).toContain('.user-delete-button')
    expect(styles).toContain('.attachment-unavailable')
    expect(styles).toContain('.icon-button')
    expect(styles).toContain('.button-icon')
    expect(styles).toContain('.user-activity-summary')
    expect(styles).toContain('.user-activity-selected')
    expect(styles).toContain('.user-activity-list')
    expect(styles).toContain('.user-activity-message')
    expect(styles).toContain('.activity-log-modal-panel')
    expect(styles).toContain('.activity-log-list')
    expect(styles).toContain('.activity-log-item')
    expect(styles).toContain('.activity-log-message')

    expect(html).not.toContain('upload-file')
    expect(html).not.toContain('upload-button')
    expect(html).not.toContain('restore-button')
    expect(html).not.toContain('drop-zone')
    expect(html).not.toContain('case-name-label')
    expect(html).not.toContain('search-mode-select')
    expect(html).not.toContain('auth-theme-toggle')
    expect(html).not.toContain('auth-message')
    expect(html).not.toContain('auth-error')
    expect(html).not.toContain('id="user-management-section"')
    expect(html).not.toContain('refresh-catalog')
    expect(script).not.toContain('uploadMailbox')
    expect(script).not.toContain('restoreSession')
    expect(script).not.toContain('excludeKeywords')
    expect(html).not.toContain('LOCAL VIEWER')
  })
})
