export const API_ROUTES = {
  authLogin: '/api/auth/login',
  authMe: '/api/auth/me',
  authLogout: '/api/auth/logout',
  authPasswordResetRequest: '/api/auth/password-reset/request',
  authPasswordResetLookup: '/api/auth/password-reset/:token',
  authPasswordResetConfirm: '/api/auth/password-reset/:token/confirm',
  authInviteLookup: '/api/auth/invites/:token',
  authInviteAccept: '/api/auth/invites/:token/accept',
  authMfaChallenge: '/api/auth/mfa/challenge',
  authMfaEnrollmentStart: '/api/auth/mfa/enrollment/start',
  authMfaEnrollmentComplete: '/api/auth/mfa/enrollment/complete',
  authUsers: '/api/auth/users',
  authUser: '/api/auth/users/:username',
  authUserAccess: '/api/auth/users/:username/access',
  authUserInviteResend: '/api/auth/users/:username/invite/resend',
  authUserInvite: '/api/auth/users/:username/invite',
  authUserMfaReset: '/api/auth/users/:username/mfa/reset',
  authUserMfaEnforce: '/api/auth/users/:username/mfa/enforce',
  smtpSettings: '/api/settings/smtp',
  smtpSettingsTest: '/api/settings/smtp/test',
  activityLog: '/api/activity-log',
  activityLogCsv: '/api/activity-log.csv',
  loadedItemsCsv: '/api/exports/items.csv',
  reviewClearFlags: '/api/reviews/clear-flags',
  pstCatalog: '/api/psts',
  pstRemovedCatalog: '/api/psts/removed',
  pstOpen: '/api/psts/open',
  pstRemove: '/api/psts/remove',
  pstRestore: '/api/psts/restore',
  searchIndexRefresh: '/api/search/index/refresh',
  searchIndexRefreshStatus: '/api/search/index/refresh/status',
  searchFilters: '/api/search/filters',
  searchFilter: '/api/search/filters/:filterId',
  search: '/api/search',
  sessionSummary: '/api/sessions/:sessionId',
  sessionTree: '/api/sessions/:sessionId/tree',
  folderMessages: '/api/sessions/:sessionId/folders/:folderId/messages',
  folderExtract: '/api/sessions/:sessionId/folders/:folderId/messages/extract',
  messageDetail: '/api/sessions/:sessionId/messages/:messageId',
  messageExtract: '/api/sessions/:sessionId/messages/:messageId/extract',
  messageReview: '/api/sessions/:sessionId/messages/:messageId/review',
  messageExportJson: '/api/sessions/:sessionId/messages/:messageId/export.json',
  messageExportEml: '/api/sessions/:sessionId/messages/:messageId/export.eml',
  messageAttachment: '/api/sessions/:sessionId/messages/:messageId/attachments/:attachmentIndex',
  itemDetail: '/api/items/:itemId',
  itemExportEml: '/api/items/:itemId/export.eml',
  itemAttachment: '/api/items/:itemId/attachments/:attachmentIndex',
  itemPreview: '/api/items/:itemId/preview',
  itemContent: '/api/items/:itemId/content',
  itemReview: '/api/items/:itemId/review',
  mailboxReviewQueue: '/api/sessions/:sessionId/review',
  flaggedBundleExport: '/api/exports/flagged.zip',
  openApiJson: '/api/openapi.json',
  docs: '/api/docs'
} as const

export function toOpenApiPath(pathTemplate: string): string {
  return pathTemplate.replace(/:([A-Za-z0-9_]+)/g, '{$1}')
}
